apiVersion: v2
name: daliuge-daemon
version: 1.0.0
appVersion: v1.0.0
home: https://github.com/ICRAR/daliuge/daliuge-k8s
description: DALiuGE k8s deployment
keywords:
  - daliuge
  - workflow
sources:
  - https://github.com/ICRAR/daliuge/daliuge-k8s
kubeVersion: ">=1.10.0-0"
