# we are doing a two-stage build to keep the size of
# the final image low.

# First stage build and cleanup
#FROM python:3.8-slim
FROM kernsuite/base:7
ARG BUILD_ID
LABEL stage=builder
LABEL build=$BUILD_ID
RUN apt-get update && apt-get install -y gcc python3-dev python3-venv

COPY / /daliuge

RUN cd && python3 -m venv dlg && cd /daliuge && \
    . ${HOME}/dlg/bin/activate && \
    pip install numpy && \
    pip install . && \
    apt-get remove -y gcc


FROM kernsuite/base:7
RUN apt-get update && apt-get install -y git
#COPY --from=0 /root/anaconda3/bin/dlg /root/anaconda3/bin/dlg 
#COPY --from=0 /root/anaconda3/lib/python3.7/site-packages/dlg /root/anaconda3/lib/python3.7/site-packages/dlg
#COPY --from=0 /root/anaconda3/lib/python3.7/site-packages/daliuge_common-1.0.0.dist-info \
#            /root/anaconda3/lib/python3.7/site-packages/daliuge_common-1.0.0.dist-info
COPY --from=0 /root/dlg /root/dlg
# RUN chown -R ray:users /home/ray/dlg
