apiVersion: apps/v1
kind: Deployment
metadata:
  name: daliuge-daemon-deployment-{{ .Values.deploy_id }}
  labels:
    app: daliuge-daemon-{{ .Values.deploy_id }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daliuge-daemon-{{ .Values.deploy_id }}
  template:
    metadata:
      labels:
        app: daliuge-daemon-{{ .Values.deploy_id }}
    spec:
      volumes:
        - name: dlg-mount
          hostPath:
            path: {{ .Values.dlg_root_on_cluster_nodes }}
      containers:
      - name: daliuge-daemon
        image: {{ .Values.containers.name }}
        ports:
          - containerPort: {{ .Values.containers.ports.containerPort }}
        volumeMounts:
        - mountPath: {{ .Values.dlg_root_in_container }}
          name: dlg-mount
        env:
        - name: DLG_ROOT
          valueFrom:
            configMapKeyRef:
              name: daliuge-daemon-configmap-{{ .Values.deploy_id }}
              key: dlg_root