apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: daliuge-daemon-deployment
  labels:
    app: daliuge-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daliuge-daemon
  serviceName: "daliuge"
  template:
    metadata:
      labels:
        app: daliuge-daemon
    spec:
      #affinity:
      #  podAntiAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      - labelSelector:
      #          matchExpressions:
      #            - key: app
      #              operator: In
      #              values:
      #                - daliuge-daemon
      #        topologyKey: kubernetes.io/hostname
      volumes:
        - name: dlg-mount
          hostPath:
            path: {{ .Values.dlg_root_on_cluster_nodes }}
      containers:
      - name: daliuge-daemon
        image: {{ .Values.containers.name }}
        ports:
          - containerPort: {{ .Values.containers.ports.containerPort }}
        volumeMounts:
        - mountPath: {{ .Values.dlg_root_in_container }}
          name: dlg-mount
        env:
        - name: DLG_ROOT
          valueFrom:
            configMapKeyRef:
              name: daliuge-daemon-configmap
              key: dlg_root