#!/bin/bash
#PBS -l walltime=12:00:00
#PBS -l nodes=3:ppn=1
#PBS -l mem=72gb

file_tsm=/mnt/hidata/chiles/final_products/20140112_951_1_FINAL_PRODUCTS/13B-266.sb28624226.eb28625769.56669.43262586805_calibrated_deepfield.ms
file_adios=/scratch/jason/13B-266.sb28624226.eb28625769.56669.43262586805_calibrated_deepfield_adios.ms

rm -rf $file_adios

mpirun -np 3 $PBS_O_WORKDIR/ms_converter $file_tsm $file_adios

