# To use docker later...
sudo: required

# let's go!
language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"

# We want to use docker during the tests
services:
 - docker

# Support for coveralls
before_install:
 - pip install coveralls pytest pytest-cov

# install dependencies (and daliuge itself)
install:
 - pip install -U setuptools
 - python setup.py install

# run the tests
script: "py.test --cov"

# Publish to coveralls (only once per commit, so only using one environment)
after_success:
 - coveralls

# safelist
branches:
 only:
  - master
