# let's go!
language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"

# install dependencies (and daliuge itself)
install: "python setup.py install"

# run the tests
script: "python setup.py test"

# safelist
branches:
 only:
  - master
  - travis-test
