ARG VCS_TAG
# We need the base image we build with the other Dockerfile
FROM icrar/daliuge-common:${VCS_TAG:-latest}

# RUN sudo apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata \
#     gcc g++ gdb casacore-dev clang-tidy-10 clang-tidy libboost1.71-all-dev libgsl-dev
RUN service dbus start && service avahi-daemon start && avahi-set-host-name dlg-engine
COPY / /daliuge
RUN . /dlg/bin/activate && pip install --upgrade pip && pip install wheel && cd /daliuge && \
    pip install . 

EXPOSE 9000
EXPOSE 5555
EXPOSE 6666
EXPOSE 8000
EXPOSE 8001
EXPOSE 8002

# enable the virtualenv path from daliuge-common
ENV VIRTUAL_ENV=/dlg
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
ENV DLG_ROOT="/tmp/dlg"
# starting the daemon, master and NM
CMD ["dlg", "daemon", "-vv", "-m"]
