services:
  daliuge-engine:
    image: icrar/daliuge-engine:${VCS_TAG}  # Dynamically set latest tag before running
    container_name: daliuge-engine
    hostname: dlg-engine
    shm_size: "2g"
    ipc: "shareable"
    user: "${UID}:${GID}"  # Set dynamically from environment variables
    environment:
      - DLG_ROOT=${DLG_ROOT}
    ports:
      - "5555:5555"
      - "6666:6666"
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DLG_ROOT}/workspace/settings/passwd:/etc/passwd
      - ${DLG_ROOT}/workspace/settings/group:/etc/group
      - ${DLG_ROOT}:${DLG_ROOT}
    restart: unless-stopped