#!/bin/sh
### BEGIN INIT INFO
# Provides:        eagle-server
# Required-Start:  $all
# Required-Stop:   $local_fs $network
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: EAGLE server daemon
### END INIT INFO
#
#
# chkconfig: 2345 99 70
# description: Starts and stops the EAGLE server as a daemon

# See how we were called.
RETVAL=0
# RH, Centos, Fedora configuration style
if [ -r /etc/sysconfig/eagle ]; then
	. /etc/sysconfig/eagle
# Debian, Ubuntu configuration style
elif [ -r /etc/default/eagle ]; then
	. /etc/default/eagle
else
	echo "Missing configuration file, cannot start EAGLE" > /dev/stderr
	exit 1
fi

case "$1" in
	start)

		# Launch the server and check right away if it started correctly
		su - $USER -c "$DAEMON start"
		RETVAL=$?
		if [ $RETVAL -eq 0 ]; then
			echo "Successfully started EAGLE server, checking it started correctly"
			$0 status
			RETVAL=$?
			if [ $RETVAL -ne 0 ]; then
				echo "EAGLE server didn't come up in time, shuttinig it down"
				$0 stop
			fi
		fi
		;;
	stop)
		echo "Shutting down EAGLE server"
		su - $USER -c "$DAEMON stop"
		RETVAL=$?
		;;
	status)
		echo "Checking EAGLE server status"
		su - $USER -c "$DAEMON status" &> /dev/null
		RETVAL=$?
		;;
	restart)
		echo -n "Restarting EAGLE server"
		$0 stop
		$0 start
		RETVAL=$?
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart}"
		RETVAL=1
esac

exit $RETVAL
