apiVersion: v1
kind: Service
metadata:
  name: daliuge-daemon-service
spec:
  selector:
    app: daliuge-daemon
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containers.ports.containerPort }}
