name: Generate component palettes

on: [push, pull_request]

jobs:

  run_tests:
    name: Generate component palettes
    runs-on: ubuntu-20.04
    env:
      PROJECT_NAME: daliuge
      GIT_REPO: https://github.com/ICRAR/daliuge
      GITHUB_USERNAME: eagle.updater

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y doxygen xsltproc
          pip install BlockDAG
          pip install dlg_paletteGen

      - name: Configure git
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_USERNAME@gmail.com

      - name: Environment variables
        run: |
          OUTPUT_FILENAME=$PROJECT_NAME-${GITHUB_REF_NAME/\//_}
          echo "PROJECT_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "OUTPUT_FILENAME=$OUTPUT_FILENAME" >> $GITHUB_ENV

      - name: Create palettes
        run: |
          dlg_paletteGen -r -t daliuge ./ $OUTPUT_FILENAME.palette
          dlg_paletteGen -r -t template ./ $OUTPUT_FILENAME-template.palette

      - name: Commit palettes to EAGLE
        env:
          EAGLE_UPDATER_TOKEN: ${{ secrets.EAGLE_UPDATER_TOKEN }}
          PALETTE_TOKEN: ${{ secrets.PALETTE_TOKEN }}
        run: |
          git clone https://$PALETTE_TOKEN@github.com/ICRAR/EAGLE-graph-repo
          mkdir -p EAGLE-graph-repo/$PROJECT_NAME
          mv $OUTPUT_FILENAME.palette EAGLE-graph-repo/$PROJECT_NAME/
          mv $OUTPUT_FILENAME-template.palette EAGLE-graph-repo/$PROJECT_NAME/
          cd EAGLE-graph-repo
          git add *
          git diff-index --quiet HEAD || git commit -m "Automatically generated DALiuGE palette (branch $GITHUB_REF_NAME, commit $PROJECT_VERSION)"
          git push
