name: Build and Push Docker Images

on: push

jobs:
  build-common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Git Tag
        run: |
          VERSION=$(cat daliuge-common/VERSION)
          echo "TAG=$VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push daliuge-common
        working-directory: daliuge-common
        run: |
          docker build -t icrar/daliuge-common:$TAG -f docker/Dockerfile .
          docker push icrar/daliuge-common:$TAG

  build-engine:
    needs: build-common
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Git Tag
        run: |
          VERSION=$(cat daliuge-engine/VERSION)
          echo "TAG=$VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build engine
        working-directory: daliuge-engine
        run: |
          docker build --build-arg VCS_TAG=$TAG --no-cache -t icrar/daliuge-engine:$TAG -f docker/Dockerfile .
          
          curl -sL https://raw.githubusercontent.com/slimtoolkit/slim/master/scripts/install-slim.sh | sudo -E bash -
          slim build --include-shell \
            --include-path /etc --include-path /usr/local/lib --include-path /usr/local/bin --include-path /usr/lib/python3.12 \
            --include-path /usr/lib/python3 --include-bin /usr/bin/hostname --include-path /dlg --include-path /daliuge \
            --include-bin /usr/sbin/service --publish-exposed-ports=true \
            --http-probe=false --continue-after 5 --tag=icrar/daliuge-engine.slim:$TAG \
            icrar/daliuge-engine:$TAG
          
          docker push icrar/daliuge-engine:$TAG
          docker push icrar/daliuge-engine.slim:$TAG

