name: Build and Push Docker Images

on: push

jobs:
  build-common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Git Tag
        run: |
          VERSION=$(cat daliuge-common/VERSION)
          echo "TAG=$VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push daliuge-common
        working-directory: daliuge-common
        run: |
          docker build -t icrar/daliuge-common:$TAG -f docker/Dockerfile .
          docker push icrar/daliuge-common:$TAG

  build-engine:
    needs: build-common
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Git Tag
        run: |
          VERSION=$(cat daliuge-common/VERSION)
          echo "TAG=$VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push daliuge-engine
        working-directory: daliuge-engine
        run: |
          docker build --build-arg VCS_TAG=$TAG --no-cache -t icrar/daliuge-engine:$TAG -f docker/Dockerfile .
          docker push icrar/daliuge-engine:$TAG