name: Run unit tests

on:
  push:
    branches:
      - master  #  Only run on pushes to master
  pull_request:
    types: [opened, synchronize]  # Run on PRs from any branch

jobs:
  run_all:
    name: Run all daliuge tests with python ${{matrix.python-version}}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.10"
          - python-version:  "3.11"
          - python-version:  "3.12"
          - python-version:  "3.13"
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: make local

      - name: Run tests
        run: make test

      - name: Update to coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
        run: coveralls --service=github


  finish:
    needs: [run_all]
    runs-on: ubuntu-22.04
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
